### ISSUE TITLE
苹果机死循环

### ISSUE THREAD

**Issue by ssb22** [fastcws/fastcws#1]
问题是苹果机的`in_avail`一直是0，这是个绕过: 在`include/fastcws/sentence_split/tokenizer.hpp`:

    size_t sz = std::min<size_t>(buffer.size(), is_.rdbuf()->in_avail());
    #ifdef __APPLE__
    if (sz==0) sz=1;
    #endif

**Comment by omegacoleman** [comment]
谢谢，已通过 c1efc79 修复。我想这个修复不限于 apple，因为可能还有其他的 istream& 不支持 rdbuf()->in_avail()，以及还需要检查上面 peek() 的 eofbit 退出状态。
```c++
if (!is_.eof() && sz == 0) { // for impl which doesn't support rdbuf()->in_avail()
	sz = 1;
}
```
