### ISSUE TITLE
cmake --build build 时报错

### ISSUE THREAD

**Issue by yyzworker** [fastcws/fastcws#5]
cmake --build build时报错
[root@idtcentos7 fastcws]# cmake --build build
[  1%] Building C object external/zlib/CMakeFiles/zlib.dir/adler32.o
[  2%] Building C object external/zlib/CMakeFiles/zlib.dir/compress.o
[  3%] Building C object external/zlib/CMakeFiles/zlib.dir/crc32.o
[  4%] Building C object external/zlib/CMakeFiles/zlib.dir/deflate.o
[  5%] Building C object external/zlib/CMakeFiles/zlib.dir/gzclose.o
[  6%] Building C object external/zlib/CMakeFiles/zlib.dir/gzlib.o
[  7%] Building C object external/zlib/CMakeFiles/zlib.dir/gzread.o
[  8%] Building C object external/zlib/CMakeFiles/zlib.dir/gzwrite.o
[  9%] Building C object external/zlib/CMakeFiles/zlib.dir/inflate.o
[ 10%] Building C object external/zlib/CMakeFiles/zlib.dir/infback.o
[ 11%] Building C object external/zlib/CMakeFiles/zlib.dir/inftrees.o
[ 12%] Building C object external/zlib/CMakeFiles/zlib.dir/inffast.o
[ 13%] Building C object external/zlib/CMakeFiles/zlib.dir/trees.o
[ 14%] Building C object external/zlib/CMakeFiles/zlib.dir/uncompr.o
[ 15%] Building C object external/zlib/CMakeFiles/zlib.dir/zutil.o
[ 17%] Linking C shared library libz.so
[ 17%] Built target zlib
[ 18%] Building C object external/zlib/CMakeFiles/zlibstatic.dir/adler32.o
[ 19%] Building C object external/zlib/CMakeFiles/zlibstatic.dir/compress.o
[ 20%] Building C object external/zlib/CMakeFiles/zlibstatic.dir/crc32.o
[ 21%] Building C object external/zlib/CMakeFiles/zlibstatic.dir/deflate.o
[ 22%] Building C object external/zlib/CMakeFiles/zlibstatic.dir/gzclose.o
[ 23%] Building C object external/zlib/CMakeFiles/zlibstatic.dir/gzlib.o
[ 24%] Building C object external/zlib/CMakeFiles/zlibstatic.dir/gzread.o
[ 25%] Building C object external/zlib/CMakeFiles/zlibstatic.dir/gzwrite.o
[ 26%] Building C object external/zlib/CMakeFiles/zlibstatic.dir/inflate.o
[ 27%] Building C object external/zlib/CMakeFiles/zlibstatic.dir/infback.o
[ 28%] Building C object external/zlib/CMakeFiles/zlibstatic.dir/inftrees.o
[ 29%] Building C object external/zlib/CMakeFiles/zlibstatic.dir/inffast.o
[ 30%] Building C object external/zlib/CMakeFiles/zlibstatic.dir/trees.o
[ 31%] Building C object external/zlib/CMakeFiles/zlibstatic.dir/uncompr.o
[ 32%] Building C object external/zlib/CMakeFiles/zlibstatic.dir/zutil.o
[ 34%] Linking C static library libz.a
[ 34%] Built target zlibstatic
[ 35%] Building C object external/zlib/CMakeFiles/example.dir/test/example.o
[ 36%] Linking C executable example
[ 36%] Built target example
[ 37%] Building C object external/zlib/CMakeFiles/minigzip.dir/test/minigzip.o
/root/fastcws/external/zlib/test/minigzip.c: In function ‘file_uncompress’:
/root/fastcws/external/zlib/test/minigzip.c:503:5: error: unknown type name ‘z_size_t’
     z_size_t len = strlen(file);
     ^
gmake[2]: *** [external/zlib/CMakeFiles/minigzip.dir/test/minigzip.o] Error 1
gmake[1]: *** [external/zlib/CMakeFiles/minigzip.dir/all] Error 2
gmake: *** [all] Error 2

**Comment by omegacoleman** [comment]
感谢汇报，看起来是此问题：https://github.com/madler/zlib/issues/772

从上游的反馈来看，修改external/zlib/CMakeLists.txt可以解决此问题：https://github.com/madler/zlib/pull/343

或者，由于minigzip在本项目中没有使用，直接移除掉相关的部分也可以
